// <auto-generated />
using FlippingTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FlippingTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180814062123_MoreItems")]
    partial class MoreItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlippingTracker.Models.Current", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("price");

                    b.Property<string>("trend");

                    b.HasKey("id");

                    b.ToTable("Current");
                });

            modelBuilder.Entity("FlippingTracker.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Currentid");

                    b.Property<int?>("Todayid");

                    b.Property<string>("description");

                    b.Property<string>("icon");

                    b.Property<string>("icon_large");

                    b.Property<bool>("members");

                    b.Property<string>("name");

                    b.Property<string>("price");

                    b.Property<string>("trend");

                    b.Property<string>("type");

                    b.Property<string>("typeIcon");

                    b.HasKey("id");

                    b.HasIndex("Currentid");

                    b.HasIndex("Todayid");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FlippingTracker.Models.Today", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("price");

                    b.Property<string>("trend");

                    b.HasKey("id");

                    b.ToTable("Today");
                });

            modelBuilder.Entity("FlippingTracker.Models.Item", b =>
                {
                    b.HasOne("FlippingTracker.Models.Current", "Current")
                        .WithMany()
                        .HasForeignKey("Currentid");

                    b.HasOne("FlippingTracker.Models.Today", "Today")
                        .WithMany()
                        .HasForeignKey("Todayid");
                });
#pragma warning restore 612, 618
        }
    }
}
